pipeline {
    agent any

    stages {
        stage ('Compile Stage') {
            steps {
                withMaven(maven : 'Maven_3.5.0') {
                    echo '[INFO] compile stage'
                }
            }
        }

        stage ('Testing Stage') {
            steps {
                withMaven(maven : 'Maven_3.5.0') {
                    echo '[INFO] testing stage '
                }
            }
        }

        stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'Maven_3.5.0') {
                    echo '[INFO] deployment stage'
                }
            }
        }
    }

    post {
        always {
            echo '[INFO] This will always run'
        }
        success {
            echo '[INFO] This will run only if successful'
        }
        failure {
            echo '[INFO] This will run only if failed'
        }
        unstable {
        echo '[INFO] This will run only if the run was marked as unstable'
        }
        changed {
            echo '[INFO] This will run only if the state of the Pipeline has changed'
            echo '[INFO] For example, if the Pipeline was previously failing but is now successful'
        }
    }
}